# R/zzz.R

.onAttach <- function(libname, pkgname) {
  packageStartupMessage("

---
**Warning:**

Users of this package must insert their own OpenAI API key to run the Shiny app. Please note that OpenAI charges for the use of their API, and these costs are associated with the predefined prompts generated by the application using the user's uploaded list of species. Users are responsible for any costs incurred through their use of the OpenAI API.

We strongly advise users to read the code before running the application. By running the code, users explicitly agree to the following terms and conditions:

1. **Acceptance of Costs**: Users accept full responsibility for any charges incurred through their use of the OpenAI API.
2. **Acknowledgment of Risk**: Users acknowledge that the use of third-party services, including the OpenAI API, involves potential costs and liabilities for which they are solely responsible.
3. **No Developer Liability**: The developers of this package do not accept any responsibility for charges or any other liabilities arising from the use of the OpenAI API.

By proceeding to use this application, you confirm that you have read, understood, and agree to these terms. If you do not agree to these terms, do not use this software.

This package is distributed under the GPLv3 License, and your use of this package is also subject to the terms of that license.

---")
}
